version: '3.4'

volumes:
  cache:
  log:
  vendor:

services:
  app:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app/public
    build:
      context: .
    volumes:
    - .:/var/www/html
    - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    - cache:/var/www/html/app/var/cache
    - log:/var/www/html/app/var/log
    - vendor:/var/www/html/app/vendor